# Generated by Django 5.2.4 on 2025-08-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_rename_members_list_board_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_to_do_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='ticket_count',
        ),
    ]
