# Generated by Django 5.2.4 on 2025-08-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0007_alter_task_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
