# Generated by Django 5.2.4 on 2025-08-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0012_remove_comment_creator_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='board',
        ),
    ]
