# Generated by Django 5.2.4 on 2025-08-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.CharField(default='1', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='fullname',
            field=models.CharField(default='1', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='password',
            field=models.CharField(default='1', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='repeated_password',
            field=models.CharField(default='1', max_length=63),
            preserve_default=False,
        ),
    ]
