# Generated by Django 5.2.4 on 2025-08-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_useraccount_email_useraccount_fullname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
